# Generated by Django 4.2.3 on 2023-07-08 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdatos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sdatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamanio', models.IntegerField()),
                ('habitaciones', models.IntegerField()),
                ('banos', models.IntegerField()),
                ('estacionamiento', models.IntegerField()),
                ('piscina', models.IntegerField()),
                ('distrito', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.DeleteModel(
            name='TuModelo',
        ),
    ]
